# -*- mode: python ; coding: utf-8 -*-


block_cipher = None


a = Analysis(['scraper_app.py'],
             pathex=[
			 'C:\\Users\\Tyler\\Desktop\\Work Stuff\\FiWize\\vehicle_data_tracker\\vehicle_data_tracker',
			 'C:\\Users\\Tyler\\Desktop\\Work Stuff\\FiWize\\vehicle_data_tracker\\vehicle_data_tracker\\spiders',
			 'C:\\Users\\Tyler\\.virtualenvs\\fiwize_vehicle_data_tracker',
			 'C:\\Users\\Tyler\\.virtualenvs\\fiwize_vehicle_data_tracker\\Scripts',
			 'C:\\Users\\Tyler\\.virtualenvs\\fiwize_vehicle_data_tracker\\Lib\\site-packages',
			 # 'C:\\Users\\Tyler\\.virtualenvs\\fiwize_vehicle_data_tracker\\Lib\\site-packages\\scrapy',
			 # 'C:\\users\\tyler\\appdata\\local\\programs\\python\\python38\\Lib\\site-packages',
			 # 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x86'
			 ],
             binaries=[],
             datas=[('.\\spiders\\',		'.\\vehicle_data_tracker\\spiders\\'),
                    ('..\\scrapy.cfg',		'.\\vehicle_data_tracker\\'),
					('.\\settings.py',		'.\\vehicle_data_tracker\\'),
					('.\\items.py',			'.\\vehicle_data_tracker\\'),
					('.\\utilities.py',		'.\\vehicle_data_tracker\\'),
					('.\\pipelines.py',		'.\\vehicle_data_tracker\\'),
                    ('.\\middlewares.py',	'.\\vehicle_data_tracker\\'),
                    ('.\\__init__.py',		'.\\vehicle_data_tracker\\'),
					('.\\settings.py',		'.\\vehicle_data_tracker\\spiders\\vehicle_data_tracker\\'),
					('.\\items.py',			'.\\vehicle_data_tracker\\spiders\\vehicle_data_tracker\\'),
					('.\\utilities.py',		'.\\vehicle_data_tracker\\spiders\\vehicle_data_tracker\\'),
					('.\\pipelines.py',		'.\\vehicle_data_tracker\\spiders\\vehicle_data_tracker\\'),
					('.\\middlewares.py',	'.\\vehicle_data_tracker\\spiders\\vehicle_data_tracker\\'),
					('.\\media\\',			'.\\media\\'),
					],
             hiddenimports=['vehicle_data_tracker.spiders', 'vehicle_data_tracker.pipelines'],
             # hookspath=['.\\hooks\\'],
			 hookspath=[],
             hooksconfig={},
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
			 
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,  
          [],
          name='scraper',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          upx_exclude=[],
          runtime_tmpdir=None,
          console=False,
          disable_windowed_traceback=False,
          target_arch=None,
          codesign_identity=None,
          entitlements_file=None)
		  
# exe = EXE(pyz,
          # a.scripts,
          # [],
          # exclude_binaries=True,
          # name='scraper',
          # debug=False,
          # bootloader_ignore_signals=False,
          # strip=False,
          # upx=True,
          # console=True,
          # disable_windowed_traceback=False,
          # target_arch=None,
          # codesign_identity=None,
          # entitlements_file=None )
# coll = COLLECT(exe,
               # a.binaries,
               # a.zipfiles,
               # a.datas, 
               # strip=False,
               # upx=True,
               # upx_exclude=[],
               # name='scraper')
